<Project Sdk="Godot.NET.Sdk/4.3.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <!-- Exclude test projects from the godot project - don't need those in a game/app! -->
    <DefaultItemExcludes>$(DefaultItemExcludes);source/Tests/**/*</DefaultItemExcludes>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>